export const urgentNeeds: any = [
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Paper Towel",
        "notes": "",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "10AM - 5PM",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Toilet Paper",
        "notes": "",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Rags",
        "notes": "",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Mops",
        "notes": "",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Brooms",
        "notes": "",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Buckets",
        "notes": "",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Hygiene Kits",
        "notes": "",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Winter Items",
        "notes": "",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Pet Food",
        "notes": "",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Living Essentials",
        "notes": "",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Men Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Women Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Children Boy Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Children Girl Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Baby Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "8300 Longworth St",
        "hours": "",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Patton Park",
        "item": "Toiletries",
        "notes": "",
        "status": "Urgently Needed",
        "location": "2301 Woodmere",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Patton Park",
        "item": "Baby Essentials",
        "notes": "",
        "status": "Urgently Needed",
        "location": "2301 Woodmere",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Patton Park",
        "item": "Cleaning Suplies",
        "notes": "",
        "status": "Urgently Needed",
        "location": "2301 Woodmere",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Patton Park",
        "item": "Volunteers",
        "notes": "",
        "status": "Urgently Needed",
        "location": "2301 Woodmere",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Hygiene Products",
        "notes": "",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "",
        "phone": "313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Cold & Flu Medicine ",
        "notes": "",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "",
        "phone": "313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Space Heaters",
        "notes": "",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "",
        "phone": "313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Diapers",
        "notes": "",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "",
        "phone": "313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Baby Formula",
        "notes": "",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "",
        "phone": "313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Blankets",
        "notes": "",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "",
        "phone": "313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Scarfs",
        "notes": "",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "",
        "phone": "313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Gloves",
        "notes": "",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "",
        "phone": "313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Hats",
        "notes": "",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "",
        "phone": "313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Pet Food",
        "notes": "",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "",
        "phone": "313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Pet Cages",
        "notes": "",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "",
        "phone": "313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Basic Health & Medical Suport",
        "notes": "",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Medication Replacements",
        "notes": "",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Medical Equipment",
        "notes": "",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Nurses",
        "notes": "",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Diapers",
        "notes": "",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Baby Formula",
        "notes": "",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Mental Health Services",
        "notes": "",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Eletric Heaters",
        "notes": "",
        "status": "Urgently Needed",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Hygiene Products",
        "notes": "",
        "status": "Urgently Needed",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Diapers",
        "notes": "",
        "status": "Urgently Needed",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Baby Wipes",
        "notes": "",
        "status": "Urgently Needed",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Cleaning Suplies",
        "notes": "",
        "status": "Urgently Needed",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Sidewalk Salt",
        "notes": "",
        "status": "Urgently Needed",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Blankets",
        "notes": "",
        "status": "Urgently Needed",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Laundry Detergent",
        "notes": "",
        "status": "Urgently Needed",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Air Matresses",
        "notes": "",
        "status": "Urgently Needed",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Men Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Women Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Children Girl Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Children Boy Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Baby Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Menstrual Supplies",
        "notes": "",
        "status": "Have Available",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Pet Supplies",
        "notes": "",
        "status": "Have Available",
        "location": "",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Cleaning Suplies",
        "notes": "",
        "status": "Urgently Needed",
        "location": "1953 Military St",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Mops",
        "notes": "",
        "status": "Urgently Needed",
        "location": "1953 Military St",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Heavy Duty Garbage Bags",
        "notes": "",
        "status": "Urgently Needed",
        "location": "1953 Military St",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Menstrual Supplies",
        "notes": "",
        "status": "Urgently Needed",
        "location": "1953 Military St",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Baby Items",
        "notes": "",
        "status": "Urgently Needed",
        "location": "1953 Military St",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Volunteers",
        "notes": "",
        "status": "Urgently Needed",
        "location": "1953 Military St",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Men Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "1953 Military St",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Women Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "1953 Military St",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Children Girl Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "1953 Military St",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Children Boy Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "1953 Military St",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Baby Clothing",
        "notes": "",
        "status": "Have Available",
        "location": "1953 Military St",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Hygiene Essentials",
        "notes": "",
        "status": "Have Available",
        "location": "1953 Military St",
        "hours": "",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Detroiters",
        "item": "Cleaning Suplies",
        "notes": "",
        "status": "Urgently Needed",
        "location": "--------",
        "hours": "--------",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Detroiters",
        "item": "Socks",
        "notes": "",
        "status": "Urgently Needed",
        "location": "--------",
        "hours": "--------",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Detroiters",
        "item": "Waterproof Shoes",
        "notes": "",
        "status": "Urgently Needed",
        "location": "--------",
        "hours": "--------",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Detroiters",
        "item": "Pet Food",
        "notes": "",
        "status": "Have Available",
        "location": "--------",
        "hours": "--------",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Detroiters",
        "item": "Pet Supplies",
        "notes": "",
        "status": "Have Available",
        "location": "--------",
        "hours": "--------",
        "social": "",
        "phone": ""
    },
    {
        "datePosted": "2025-02-24",
        "organization": "City of Detroit",
        "item": "Furnaces",
        "notes": "",
        "status": "Have Available",
        "location": "",
        "hours": "--------",
        "social": "@cityofdetroit",
        "phone": "(313) 774-5261"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "City of Detroit",
        "item": "Hot Water",
        "notes": "",
        "status": "Have Available",
        "location": "",
        "hours": "--------",
        "social": "@cityofdetroit",
        "phone": "(313) 774-5261"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "City of Detroit",
        "item": "Heaters",
        "notes": "",
        "status": "Have Available",
        "location": "",
        "hours": "--------",
        "social": "@cityofdetroit",
        "phone": "(313) 774-5261"
    }
] as const ;