export const data: any = [
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Paper Towel",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "social": "@unidetroit"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Paper Towel",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "social": "@unidetroit"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "BBB",
        "itemCategory": "Cleaning",
        "status": "Have Available",
        "social": "@unidetroit"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "BBB",
        "itemCategory": "CCC",
        "status": "Have Available",
        "social": "@unidetroit"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "BBB",
        "itemCategory": "AAA",
        "status": "Have Available",
        "social": "@unidetroit"
    },
]

const availableCount =[
    {
        id:0,
        label:'AAA',
        value: 1,
    },
    {
        id:0,
        label:'CCC',
        value: 1,
    },
    {
        id:0,
        label:'Cleaning',
        value: 1,
    },
]

export const ResourcesTable: any = [
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Paper Towel",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "8300 Longworth St ",
        "hours": "02/24-25/2025  @9am-8pm",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Toilet Paper",
        "itemCategory": "Hygiene",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "02/24-25/2025  @9am-8pm",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Rags",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "02/24-25/2025  @9am-8pm",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Mops",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "02/24-25/2025  @9am-8pm",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Laundry Detergent",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "02/24-25/2025  @9am-8pm",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Garbage Bags",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "02/24-25/2025  @9am-8pm",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Brooms",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "02/24-25/2025  @9am-8pm",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Buckets",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "02/24-25/2025  @9am-8pm",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Hygiene Kits",
        "itemCategory": "Hygiene",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "02/24-25/2025  @9am-8pm",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Winter Items",
        "itemCategory": "Winter Essentials",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "02/24-25/2025  @9am-8pm",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Pet Food",
        "itemCategory": "Pet",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "02/24-25/2025  @9am-8pm",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "UNI",
        "item": "Living Essentials",
        "itemCategory": "Other",
        "status": "Urgently Needed",
        "location": "8300 Longworth St",
        "hours": "02/24-25/2025  @9am-8pm",
        "social": "@unidetroit",
        "phone": "(313)841-4447"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Patton Park",
        "item": "Toiletries",
        "itemCategory": "Hygiene",
        "status": "Urgently Needed",
        "location": "2301 Woodmere St",
        "hours": "M-F @8:00am-7:00pm",
        "social": "------",
        "phone": "------"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Patton Park",
        "item": "Baby Essentials",
        "itemCategory": "Babies/Children",
        "status": "Urgently Needed",
        "location": "2301 Woodmere St",
        "hours": "M-F @8:00am-7:00pm",
        "social": "------",
        "phone": "------"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Patton Park",
        "item": "Cleaning Suplies",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "2301 Woodmere St",
        "hours": "M-F @8:00am-7:00pm",
        "social": "------",
        "phone": "------"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Patton Park",
        "item": "Volunteers",
        "itemCategory": "Volunteering",
        "status": "Urgently Needed",
        "location": "2301 Woodmere St",
        "hours": "M-F @8:00am-7:00pm",
        "social": "------",
        "phone": "------"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Hygiene Products",
        "itemCategory": "Hygiene",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "@sdbadet",
        "phone": "(313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Cold & Flu Medicine ",
        "itemCategory": "Medical",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "@sdbadet",
        "phone": "(313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Space Heaters",
        "itemCategory": "Winter Essentials",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "@sdbadet",
        "phone": "(313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Diapers",
        "itemCategory": "Babies/Children",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "@sdbadet",
        "phone": "(313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Baby Formula",
        "itemCategory": "Babies/Children",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "@sdbadet",
        "phone": "(313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Blankets",
        "itemCategory": "Winter Essentials",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "@sdbadet",
        "phone": "(313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Scarfs",
        "itemCategory": "Winter Essentials",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "@sdbadet",
        "phone": "(313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Gloves",
        "itemCategory": "Winter Essentials",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "@sdbadet",
        "phone": "(313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Hats",
        "itemCategory": "Winter Essentials",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "@sdbadet",
        "phone": "(313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Pet Food",
        "itemCategory": "Pet",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "@sdbadet",
        "phone": "(313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "SDBA",
        "item": "Pet Cages",
        "itemCategory": "Pet",
        "status": "Urgently Needed",
        "location": " 7752 Vernor Hwy",
        "hours": "M-F @9:00am-5pm",
        "social": "@sdbadet",
        "phone": "(313) 842-0986"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Basic Health & Medical Suport",
        "itemCategory": "Medical",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy Detoit MI 48209",
        "hours": "02/22-23/2025 @10am-6pm",
        "social": "------",
        "phone": "(313-554-2025"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Medication Replacements",
        "itemCategory": "Medical",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy Detoit MI 48209",
        "hours": "02/22-23/2025 @10am-6pm",
        "social": "------",
        "phone": "(313-554-2025"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Medical Equipment",
        "itemCategory": "Medical",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy Detoit MI 48209",
        "hours": "02/22-23/2025 @10am-6pm",
        "social": "------",
        "phone": "(313-554-2025"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Nurses",
        "itemCategory": "Medical",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy Detoit MI 48209",
        "hours": "02/22-23/2025 @10am-6pm",
        "social": "------",
        "phone": "(313-554-2025"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Diapers",
        "itemCategory": "Babies/Children",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy Detoit MI 48209",
        "hours": "02/22-23/2025 @10am-6pm",
        "social": "------",
        "phone": "(313-554-2025"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Baby Formula",
        "itemCategory": "Babies/Children",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy Detoit MI 48209",
        "hours": "02/22-23/2025 @10am-6pm",
        "social": "------",
        "phone": "(313-554-2025"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "La SED",
        "item": "Mental Health Services",
        "itemCategory": "Medical",
        "status": "Have Available",
        "location": "7150 W Vernor Hwy Detoit MI 48209",
        "hours": "02/22-23/2025 @10am-6pm",
        "social": "------",
        "phone": "(313-554-2025"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Eletric Heaters",
        "itemCategory": "Winter Essentials",
        "status": "Urgently Needed",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Hygiene Products",
        "itemCategory": "Hygiene",
        "status": "Urgently Needed",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Diapers",
        "itemCategory": "Babies/Children",
        "status": "Urgently Needed",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Baby Wipes",
        "itemCategory": "Babies/Children",
        "status": "Urgently Needed",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Cleaning Suplies",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Sidewalk Salt",
        "itemCategory": "Other",
        "status": "Urgently Needed",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Blankets",
        "itemCategory": "Winter Essentials",
        "status": "Urgently Needed",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Laundry Detergent",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Air Matresses",
        "itemCategory": "Other",
        "status": "Urgently Needed",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Men Clothing",
        "itemCategory": "Clothing",
        "status": "Have Available",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Women Clothing",
        "itemCategory": "Clothing",
        "status": "Have Available",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Children Girl Clothing",
        "itemCategory": "Clothing",
        "status": "Have Available",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Children Boy Clothing",
        "itemCategory": "Clothing",
        "status": "Have Available",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Baby Clothing",
        "itemCategory": "Clothing",
        "status": "Have Available",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Menstrual Supplies",
        "itemCategory": "Hygiene",
        "status": "Have Available",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "DHDC",
        "item": "Pet Supplies",
        "itemCategory": "Pet",
        "status": "Have Available",
        "location": "1211 Trumbull St",
        "hours": "M-F @10:00am-5pm",
        "social": "@amodhdc",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Cleaning Suplies",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "1953 Military St",
        "hours": "M-F @3:00pm-9:00pm",
        "social": "@santosdetroit",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Mops",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "1953 Military St",
        "hours": "M-F @3:00pm-9:00pm",
        "social": "@santosdetroit",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Heavy Duty Garbage Bags",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "1953 Military St",
        "hours": "M-F @3:00pm-9:00pm",
        "social": "@santosdetroit",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Menstrual Supplies",
        "itemCategory": "Hygiene",
        "status": "Urgently Needed",
        "location": "1953 Military St",
        "hours": "M-F @3:00pm-9:00pm",
        "social": "@santosdetroit",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Baby Items",
        "itemCategory": "Babies/Children",
        "status": "Urgently Needed",
        "location": "1953 Military St",
        "hours": "M-F @3:00pm-9:00pm",
        "social": "@santosdetroit",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Volunteers",
        "itemCategory": "Volunteering",
        "status": "Urgently Needed",
        "location": "1953 Military St",
        "hours": "M-F @3:00pm-9:00pm",
        "social": "@santosdetroit",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Men Clothing",
        "itemCategory": "Clothing",
        "status": "Have Available",
        "location": "1953 Military St",
        "hours": "M-F @3:00pm-9:00pm",
        "social": "@santosdetroit",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Women Clothing",
        "itemCategory": "Clothing",
        "status": "Have Available",
        "location": "1953 Military St",
        "hours": "M-F @3:00pm-9:00pm",
        "social": "@santosdetroit",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Children Girl Clothing",
        "itemCategory": "Clothing",
        "status": "Have Available",
        "location": "1953 Military St",
        "hours": "M-F @3:00pm-9:00pm",
        "social": "@santosdetroit",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Children Boy Clothing",
        "itemCategory": "Clothing",
        "status": "Have Available",
        "location": "1953 Military St",
        "hours": "M-F @3:00pm-9:00pm",
        "social": "@santosdetroit",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Baby Clothing",
        "itemCategory": "Clothing",
        "status": "Have Available",
        "location": "1953 Military St",
        "hours": "M-F @3:00pm-9:00pm",
        "social": "@santosdetroit",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Santos Chruch",
        "item": "Hygiene Essentials",
        "itemCategory": "Hygiene",
        "status": "Have Available",
        "location": "1953 Military St",
        "hours": "M-F @3:00pm-9:00pm",
        "social": "@santosdetroit",
        "phone": "-----"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Detroiters",
        "item": "Cleaning Suplies",
        "itemCategory": "Cleaning",
        "status": "Urgently Needed",
        "location": "--------",
        "hours": "--------",
        "social": "--------",
        "phone": "(313)704-5392"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Detroiters",
        "item": "Socks",
        "itemCategory": "Other",
        "status": "Urgently Needed",
        "location": "--------",
        "hours": "--------",
        "social": "--------",
        "phone": "(313)704-5392"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Detroiters",
        "item": "Waterproof Shoes",
        "itemCategory": "Other",
        "status": "Urgently Needed",
        "location": "--------",
        "hours": "--------",
        "social": "--------",
        "phone": "(313)704-5392"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Detroiters",
        "item": "Pet Food",
        "itemCategory": "Pet",
        "status": "Have Available",
        "location": "--------",
        "hours": "--------",
        "social": "--------",
        "phone": "(313)704-5392"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "Detroiters",
        "item": "Pet Supplies",
        "itemCategory": "Pet",
        "status": "Have Available",
        "location": "--------",
        "hours": "--------",
        "social": "--------",
        "phone": "(313)704-5392"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "City of Detroit",
        "item": "Furnaces",
        "itemCategory": "Other",
        "status": "Have Available",
        "location": "--------",
        "hours": "--------",
        "social": "@cityofdetroit",
        "phone": "(313) 774-5261"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "City of Detroit",
        "item": "Hot Water",
        "itemCategory": "Other",
        "status": "Have Available",
        "location": "--------",
        "hours": "--------",
        "social": "@cityofdetroit",
        "phone": "(313) 774-5261"
    },
    {
        "datePosted": "2025-02-24",
        "organization": "City of Detroit",
        "item": "Heaters",
        "itemCategory": "Other",
        "status": "Have Available",
        "location": "--------",
        "hours": "--------",
        "social": "@cityofdetroit",
        "phone": "(313) 774-5261"
    }
] as const ;